Fix minor bugs

diff --git a/bin/enigma-qc b/bin/enigma-qc
--- a/bin/enigma-qc
+++ b/bin/enigma-qc
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-OPTS=`getopt -o s:b:v --long study-name:,bfile:,verbose -n 'enigma-qc' -- "$@"`
+OPTS=`getopt -o s:b: --long study-name:,bfile: -n 'enigma-qc' -- "$@"`
 eval set -- "$OPTS"
 
-VERBOSE=0
+VERBOSE=1
 
 while true ; do
     case "$1" in
@@ -17,7 +17,6 @@ while true ; do
                 "") shift 2 ;;
                 *) STUDY_NAME=$2 ; shift 2 ;;
             esac ;;
-        -v|--verbose) VERBOSE=1 ; shift ;;
         --) shift ; break ;;
         *) echo "Internal error!" ; exit 1 ;;
     esac
@@ -28,16 +27,8 @@ fail() {
     exit "${2-1}"  
 }
 
-if [ ! -d /data/input ]; then
-    fail "Imputation server input folder \"/data/input\" does not exist. You should create it and try again"
-fi
-
-if [ ! $(ls -A /data/input) ]; then
-    fail "Imputation server input folder \"/data/input\" is not empty. You should check and/or backup its contents, run \"rm /data/input/*\", and try again"
-fi
-
 if [[ ! -v STUDY_NAME ]]; then
-    fail "Missing required --study-name parameter"
+    fail "missing required --study-name parameter"
 fi
 
 if [[ ! -v BFILE ]]; then
@@ -66,19 +57,28 @@ run_cmd() {
     return $EXIT_CODE
 }
 
-run_cmd plink --bfile ${BFILE} --make-founders --out "lastQC" --maf 0.01 --hwe 0.000001 --make-bed --noweb
+VCF_DIRECTORY=/data/input/${STUDY_NAME}
+run_cmd mkdir -p -v ${VCF_DIRECTORY}
+
+run_cmd "awk '{ \
+if ((\$5==\"T\" && \$6==\"A\") || (\$5==\"A\" && \$6==\"T\") || (\$5==\"C\" && \$6==\"G\") || (\$5==\"G\" && \$6==\"C\")) \
+print \$2, \"ambig\"; \
+else print \$2; \
+}' ${BFILE}.bim | grep ambig | awk '{print \$1}' > ambig.list"
+
+run_cmd plink --bfile ${BFILE} --exclude "ambig.list" --make-founders --out "lastQC" --maf 0.01 --hwe 0.000001 --make-bed --noweb
 
 run_cmd "awk '{print \$2, \$1\":\"\$4}' lastQC.bim > updateSNPs.txt"
 
 run_cmd plink --bfile "lastQC" --update-name "updateSNPs.txt" --make-bed --out "lastQCb37" --noweb --list-duplicate-vars
+LASTQC="lastQCb37"
 
-export LASTQC="lastQCb37"
 if [[ $(wc -l <lastQCb37.dupvar) -ge 1 ]]; then
     run_cmd plink2 --bfile "lastQCb37" --rm-dup "exclude-mismatch" --out "lastQCb37_noduplicates" --make-bed
-    export LASTQC="lastQCb37_noduplicates"
+    LASTQC="lastQCb37_noduplicates"
 fi
 
 for CHR in {1..22}; do
     run_cmd plink2 --bfile "${LASTQC}" --chr "${CHR}" --recode "vcf" --out "${STUDY_NAME}_chr${CHR}"
-    run_cmd "vcf-sort ${STUDY_NAME}_chr${CHR}.vcf | bgzip -c > /data/input/${STUDY_NAME}_chr${CHR}.vcf.gz"
+    run_cmd "vcf-sort ${STUDY_NAME}_chr${CHR}.vcf | bgzip -c > ${VCF_DIRECTORY}/chr${CHR}.vcf.gz"
 done
diff --git a/bin/setup-hadoop b/bin/setup-hadoop
--- a/bin/setup-hadoop
+++ b/bin/setup-hadoop
@@ -3,6 +3,8 @@
 OPTS=`getopt -o n: --long n-cores: -n 'setup-hadoop' -- "$@"`
 eval set -- "$OPTS"
 
+VERBOSE=1
+
 N_CORES=4
 
 while true ; do
@@ -17,6 +19,28 @@ while true ; do
     esac
 done
 
+run_cmd() {
+    cmd="$*"
+
+    printf '%s\n' --------------------
+
+    if [ "$VERBOSE" = "1" ]; then
+	printf "$cmd\n"
+    fi
+
+    eval "$@"
+
+    EXIT_CODE=$?
+
+    if [[ $EXIT_CODE -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    fi
+
+    printf '%s\n' --------------------
+
+    return $EXIT_CODE
+}
+
 source /usr/lib/bigtop-utils/bigtop-detect-javahome
 
 export HADOOP_HOME=/usr/lib/hadoop
@@ -26,21 +50,19 @@ export HADOOP_LOG_DIR=/data/logs
 export HADOOP_PID_DIR=/data/pids
 export HADOOP_CONF_DIR=/data/config
 
-mkdir -p -v ${HADOOP_LOG_DIR} ${HADOOP_PID_DIR} ${HADOOP_CONF_DIR}
+run_cmd mkdir -p -v ${HADOOP_LOG_DIR} ${HADOOP_PID_DIR} ${HADOOP_CONF_DIR}
 
-cp -rnv ${HADOOP_HOME}/etc/hadoop/* ${HADOOP_CONF_DIR}
+run_cmd cp -rnv ${HADOOP_HOME}/etc/hadoop/* ${HADOOP_CONF_DIR}
 
-sed -e s/AMOUNT/${N_CORES}/ -e s/HOSTNAME/localhost/ /usr/bin/mapred-site-template.xml > ${HADOOP_CONF_DIR}/mapred-site.xml
+run_cmd "sed -e s/AMOUNT/${N_CORES}/ -e s/HOSTNAME/localhost/ /usr/bin/mapred-site-template.xml > ${HADOOP_CONF_DIR}/mapred-site.xml"
 
-sed s/HOSTNAME/localhost/ /usr/bin/core-site-template.xml > ${HADOOP_CONF_DIR}/core-site.xml
+run_cmd "sed s/HOSTNAME/localhost/ /usr/bin/core-site-template.xml > ${HADOOP_CONF_DIR}/core-site.xml"
 
-sed -i "s+/var/lib/hadoop-hdfs/cache+/data/hadoop/cache+g" ${HADOOP_CONF_DIR}/*
+run_cmd "sed -i s+/var/lib/hadoop-hdfs/cache+/data/hadoop/cache+g ${HADOOP_CONF_DIR}/*"
 
-sed -e s+HADOOP_LOG_DIR+${HADOOP_LOG_DIR}+ log4j.properties > ${HADOOP_CONF_DIR}/log4j.properties
+run_cmd "echo localhost > ${HADOOP_CONF_DIR}/masters"
 
-echo localhost > $HADOOP_CONF_DIR/masters
-
-cat <<EOF >> ${HADOOP_CONF_DIR}/hadoop-env.sh
+run_cmd "cat <<EOF >> ${HADOOP_CONF_DIR}/hadoop-env.sh
 
 # custom
 
@@ -52,26 +74,30 @@ export HADOOP_SECURE_DN_PID_DIR=${HADOOP_PID_DIR}
 export HADOOP_HOME_WARN_SUPPRESS=TRUE
 
 export JAVA_HOME=${JAVA_HOME}
-EOF
+EOF"
 
-hdfs namenode -format -nonInteractive -force
+if [ -d /data/hadoop ]; then
+    run_cmd rm -rf /data/hadoop
+fi
 
-/usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start namenode
-/usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start secondarynamenode
-/usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start datanode
+run_cmd hdfs namenode -format -nonInteractive -force
 
-env HADOOP_HOME=/usr/lib/hadoop-0.20-mapreduce /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start jobtracker
-env HADOOP_HOME=/usr/lib/hadoop-0.20-mapreduce /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start tasktracker
+run_cmd /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start namenode
+run_cmd /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start secondarynamenode
+run_cmd /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start datanode
 
-hadoop fs -mkdir -p /tmp
-hadoop fs -chmod -R 1777 /tmp
-hadoop fs -mkdir -p /var
-hadoop fs -mkdir -p /var/log
-hadoop fs -chmod -R 1775 /var/log
+run_cmd env HADOOP_HOME=/usr/lib/hadoop-0.20-mapreduce /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start jobtracker
+run_cmd env HADOOP_HOME=/usr/lib/hadoop-0.20-mapreduce /usr/lib/hadoop/sbin/hadoop-daemon.sh --config "${HADOOP_CONF_DIR}" start tasktracker
 
-hadoop fs -mkdir -p /data/hadoop/cache/${USER}/mapred/staging
-hadoop fs -chmod 1777 /data/hadoop/cache/${USER}/mapred/staging
-hadoop fs -chown -R ${USER} /data/hadoop/cache/${USER}
+run_cmd hadoop fs -mkdir -p /tmp
+run_cmd hadoop fs -chmod -R 1777 /tmp
+run_cmd hadoop fs -mkdir -p /var
+run_cmd hadoop fs -mkdir -p /var/log
+run_cmd hadoop fs -chmod -R 1775 /var/log
 
-hadoop fs -mkdir -p /user/${USER}
-hadoop fs -chown ${USER} /user/${USER}
+run_cmd hadoop fs -mkdir -p /data/hadoop/cache/${USER}/mapred/staging
+run_cmd hadoop fs -chmod 1777 /data/hadoop/cache/${USER}/mapred/staging
+run_cmd hadoop fs -chown -R ${USER} /data/hadoop/cache/${USER}
+
+run_cmd hadoop fs -mkdir -p /user/${USER}
+run_cmd hadoop fs -chown ${USER} /user/${USER}
diff --git a/bin/setup-imputationserver b/bin/setup-imputationserver
--- a/bin/setup-imputationserver
+++ b/bin/setup-imputationserver
@@ -1,16 +1,42 @@
 #!/bin/bash
 
+VERBOSE=1
+
+run_cmd() {
+    cmd="$*"
+
+    printf '%s\n' --------------------
+
+    if [ "$VERBOSE" = "1" ]; then
+	printf "$cmd\n"
+    fi
+
+    ( "$@" )
+
+    EXIT_CODE=$?
+
+    if [[ $EXIT_CODE -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    fi
+
+    printf '%s\n' --------------------
+
+    return $EXIT_CODE
+}
+
+run_cmd mkdir -p -v /data/cloudgene
+run_cmd cp -rnv /opt/cloudgene/* /data/cloudgene/
+
+export PATH=/data/cloudgene:${PATH}
 export HADOOP_CONF_DIR=/data/config
 
-mkdir -p /data/cloudgene
-cp -rnv /opt/cloudgene/* /data/cloudgene/
-export PATH=/data/cloudgene:${PATH}
+run_cmd cloudgene verify-cluster
 
-cloudgene verify-cluster
+run_cmd cloudgene clone /data/cloudgene/apps.yaml
 
-cloudgene clone /data/cloudgene/apps.yaml
+run_cmd chmod -R +w /data/cloudgene/apps/imputationserver  # needs to be writable because it will be used as a temp dir
+run_cmd chmod -R -w /data/cloudgene/apps/1000g-phase-3-v5  # otherwise cloudgene will delete the files on import to hadoop
 
-chmod -R +w /data/cloudgene/apps/imputationserver  # needs to be writable because it will be used as a temp dir
-chmod -R -w /data/cloudgene/apps/1000g-phase-3-v5  # otherwise cloudgene will delete the files on import to hadoop
+run_cmd mkdir -p -v /data/input /data/output
 
-mkdir -p -v /data/input /data/output
+run_cmd sed -i "s/value: auto/value: password/g" /data/cloudgene/apps/imputationserver/*/*.yaml
