Fix code style

diff --git a/bin/enigma-mds b/bin/enigma-mds
--- a/bin/enigma-mds
+++ b/bin/enigma-mds
@@ -3,7 +3,7 @@
 OPTS=`getopt -o b:s: --long study-name:,bfile: -n 'enigma-mds' -- "$@"`
 eval set -- "$OPTS"
 
-VERBOSE=1
+verbose=1
 
 while true ; do
     case "$1" in
@@ -12,7 +12,7 @@ while true ; do
                 "") shift 2 ;;
                 *) BFILE=$2 ; shift 2 ;;
             esac ;;
-        -v|--verbose) VERBOSE=1 ; shift ;;
+        -v|--verbose) verbose=1 ; shift ;;
         --) shift ; break ;;
         *) echo "Internal error!" ; exit 1 ;;
     esac
@@ -32,21 +32,21 @@ run_cmd() {
 
     printf '%s\n' --------------------
 
-    if [ "$VERBOSE" = "1" ]; then
+    if [ "${verbose}" = "1" ]; then
 	echo "$cmd"
     fi
 
     eval "$@"
 
-    EXIT_CODE=$?
+    exit_code=$?
 
-    if [[ $EXIT_CODE -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    if [[ ${exit_code} -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
 
-    return $EXIT_CODE
+    return ${exit_code}
 }
 
 # code starts here
diff --git a/bin/stop-hadoop b/bin/stop-hadoop
--- a/bin/stop-hadoop
+++ b/bin/stop-hadoop
@@ -1,31 +1,32 @@
 #!/usr/bin/env bash
 
-VERBOSE=1
+verbose=1
 
 run_cmd() {
     cmd="$*"
 
     printf '%s\n' --------------------
 
-    if [ "$VERBOSE" = "1" ]; then
+    if [ "${verbose}" = "1" ]; then
 	printf "$cmd\n"
     fi
 
     eval "$@"
 
-    EXIT_CODE=$?
+    exit_code=$?
 
-    if [[ $EXIT_CODE -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    if [[ ${exit_code} -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
 
-    return $EXIT_CODE
+    return ${exit_code}
 }
 
 export HADOOP_PID_DIR=/data/hadoop/pids
 
-for PID_FILE in ${HADOOP_PID_DIR}/hadoop-*.pid; do
-    run_cmd "kill \$(cat ${PID_FILE})"
+for pid_file in ${HADOOP_PID_DIR}/hadoop-*.pid; do
+    run_cmd "kill \$(cat ${pid_file})"
+    run_cmd rm pid_file
 done
