Fix `singularity` build

diff --git a/bin/enigma-mds b/bin/enigma-mds
--- a/bin/enigma-mds
+++ b/bin/enigma-mds
@@ -1,26 +1,39 @@
 #!/usr/bin/env bash
 
-OPTS=`getopt -o b:s: --long study-name:,bfile: -n 'enigma-mds' -- "$@"`
+OPTS=$(getopt -o b:s: --long study-name:,bfile: -n 'enigma-mds' -- "$@")
 eval set -- "$OPTS"
 
 verbose=1
 
-while true ; do
+while true; do
     case "$1" in
-        -b|--bfile)
-            case "$2" in
-                "") shift 2 ;;
-                *) BFILE=$2 ; shift 2 ;;
-            esac ;;
-        -v|--verbose) verbose=1 ; shift ;;
-        --) shift ; break ;;
-        *) echo "Internal error!" ; exit 1 ;;
+    -b | --bfile)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            BFILE=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    -v | --verbose)
+        verbose=1
+        shift
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "Internal error!"
+        exit 1
+        ;;
     esac
 done
 
 fail() {
-    printf '%s\n' "$1" >&2    
-    exit "${2-1}"  
+    printf '%s\n' "$1" >&2
+    exit "${2-1}"
 }
 
 if [[ ! -v BFILE ]]; then
@@ -33,15 +46,15 @@ run_cmd() {
     printf '%s\n' --------------------
 
     if [ "${verbose}" = "1" ]; then
-	echo "$cmd"
+        printf "%s\n" "${cmd}"
     fi
 
-    eval "$@"
+    ("$@")
 
     exit_code=$?
 
     if [[ ${exit_code} -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status ${exit_code}"
+        echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
diff --git a/bin/enigma-qc b/bin/enigma-qc
--- a/bin/enigma-qc
+++ b/bin/enigma-qc
@@ -1,30 +1,44 @@
 #!/usr/bin/env bash
 
-OPTS=`getopt -o s:b: --long study-name:,bfile: -n 'enigma-qc' -- "$@"`
+OPTS=$(getopt -o s:b: --long study-name:,bfile: -n 'enigma-qc' -- "$@")
 eval set -- "$OPTS"
 
 verbose=1
 
-while true ; do
+while true; do
     case "$1" in
-        -b|--bfile)
-            case "$2" in
-                "") shift 2 ;;
-                *) bfile=$2 ; shift 2 ;;
-            esac ;;
-        -s|--study-name)
-            case "$2" in
-                "") shift 2 ;;
-                *) study_name=$2 ; shift 2 ;;
-            esac ;;
-        --) shift ; break ;;
-        *) echo "Internal error!" ; exit 1 ;;
+    -b | --bfile)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            bfile=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    -s | --study-name)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            study_name=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "Internal error!"
+        exit 1
+        ;;
     esac
 done
 
 fail() {
-    printf '%s\n' "$1" >&2    
-    exit "${2-1}"  
+    printf '%s\n' "$1" >&2
+    exit "${2-1}"
 }
 
 if [[ ! -v study_name ]]; then
@@ -41,15 +55,15 @@ run_cmd() {
     printf '%s\n' --------------------
 
     if [ "${verbose}" = "1" ]; then
-	printf "$cmd\n"
+        printf "%s\n" "${cmd}"
     fi
 
-    eval "$@"
+    ("$@")
 
     exit_code=$?
 
     if [[ ${exit_code} -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status ${exit_code}"
+        echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
@@ -60,7 +74,7 @@ run_cmd() {
 # code starts here
 
 vcf_directory=/data/input/${study_name}
-run_cmd mkdir -p -v ${vcf_directory}
+run_cmd mkdir -p -v "${vcf_directory}"
 
 run_cmd "sed 's/\r$//' ${bfile}.bim | \
     awk '((\$5 == \"A\" && \$6 == \"T\") || \
@@ -69,7 +83,7 @@ run_cmd "sed 's/\r$//' ${bfile}.bim | \
           (\$5 == \"C\" && \$6 == \"G\")) { print \$2 }' > ambiguous"
 
 out="lastQC"
-run_cmd plink2 --bfile ${bfile} \
+run_cmd plink2 --bfile "${bfile}" \
     --nonfounders \
     --out "${out}" \
     --exclude "ambiguous" \
@@ -97,6 +111,6 @@ for c in {1..22} X; do
         --nonfounders \
         --out "chr${c}" \
         --chr "${c}" \
-        --export "vcf-4.2" 
+        --export "vcf-4.2"
     run_cmd "vcf-sort chr${c}.vcf | bgzip -c > ${vcf_directory}/chr${c}.vcf.gz"
 done
diff --git a/bin/imputationserver b/bin/imputationserver
--- a/bin/imputationserver
+++ b/bin/imputationserver
@@ -1,11 +1,10 @@
 #!/usr/bin/env bash
 
-opts=`getopt -o s:p: --long population:,study-name:,r2Filter: -n 'imputationserver' -- "$@"`
+opts=$(getopt -o s:p: --long population:,study-name:,r2Filter: -n 'imputationserver' -- "$@")
 
 exit_code=$?
 
-if [ ${exit_code} -ne 0  ]
-then
+if [ ${exit_code} -ne 0 ]; then
     exit ${exit_code}
 fi
 
@@ -13,31 +12,49 @@ eval set -- "$opts"
 
 verbose=1
 
-while true ; do
+while true; do
     case "$1" in
-        -s|--study-name)
-            case "$2" in
-                "") shift 2 ;;
-                *) study_name=$2 ; shift 2 ;;
-            esac ;;
-        -p|--population)
-            case "$2" in
-                "") shift 2 ;;
-                *) population=$2 ; shift 2 ;;
-            esac ;;
-        --r2Filter)
-            case "$2" in
-                "") shift 2 ;;
-                *) r2Filter=$2 ; shift 2 ;;
-            esac ;;
-        --) shift ; break ;;
-        *) echo "Internal error!" ; exit 1 ;;
+    -s | --study-name)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            study_name=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    -p | --population)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            population=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    --r2Filter)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            r2Filter=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "Internal error!"
+        exit 1
+        ;;
     esac
 done
 
 fail() {
-    printf '%s\n' "$1" >&2    
-    exit "${2-1}"  
+    printf '%s\n' "$1" >&2
+    exit "${2-1}"
 }
 
 if [[ ! -v study_name ]]; then
@@ -54,15 +71,15 @@ run_cmd() {
     printf '%s\n' --------------------
 
     if [ "$verbose" = "1" ]; then
-	printf "$cmd\n"
+        printf "%s\n" "${cmd}"
     fi
 
-    ( "$@" )
+    ("$@")
 
     exit_code=$?
 
     if [[ ${exit_code} -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status ${exit_code}"
+        echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
@@ -83,16 +100,17 @@ if [ ! -z "${r2Filter}" ]; then
     extra_flags="${extra_flags} --r2Filter ${r2Filter}"
 fi
 
-if [ -z "${USER}" ]; then 
-    export USER=$(whoami)
+if [ -z "${USER}" ]; then
+    USER=$(whoami)
+    export USER
 fi
 
-run_cmd mkdir -p -v /data/output/${study_name}
+run_cmd mkdir -p -v "/data/output/${study_name}"
 
 run_cmd cloudgene run imputationserver \
     --conf ${HADOOP_CONF_DIR} \
     --refpanel "1000g-phase-3-v5" \
-    --population ${population} \
+    --population "${population}" \
     --files "/data/input/${study_name}" \
     --output "/data/output/${study_name}" \
-    --user ${USER} ${extra_flags}
+    --user "${USER}" "${extra_flags}"
