Finish checkflip and improve usability

diff --git a/bin/enigma-mds b/bin/enigma-mds
--- a/bin/enigma-mds
+++ b/bin/enigma-mds
@@ -1,36 +1,89 @@
 #!/bin/bash
 
-export reference="/localdata/mds/HM3_b37"
+#!/usr/bin/env bash
 
-plink --bfile "${datafileraw}" --hwe "1e-6" --geno "0.05" --maf "0.01" --noweb --make-bed --out "$(basename ${datafileraw})_filtered"
+OPTS=`getopt -o b:v --long bfile:,verbose -n 'imputationserver' -- "$@"`
+eval set -- "$OPTS"
 
-awk '{print $2}' "${reference}.bim" > "HM3_b37.snplist.txt"
+VERBOSE=0
 
-plink --bfile "${datafile}" --extract "HM3_b37.snplist.txt" --make-bed --noweb --out "local"
+while true ; do
+    case "$1" in
+        -b|--bfile)
+            case "$2" in
+                "") shift 2 ;;
+                *) BFILE=$2 ; shift 2 ;;
+            esac ;;
+        -v|--verbose) VERBOSE=1 ; shift ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
 
-awk '{ \
-if (($5=="T" && $6=="A") || ($5=="A" && $6=="T") || ($5=="C" && $6=="G") || ($5=="G" && $6=="C")) \
-print $2, "ambig"; \
-else print $2; \
-}' "${datafile}.bim" | grep -v "ambig" > "local.snplist.txt"
+fail() {
+    printf '%s\n' "$1" >&2    
+    exit "${2-1}"  
+}
 
-plink --bfile "${reference}" --extract "local.snplist.txt" --make-bed --noweb --out external
+if [[ ! -v BFILE ]]; then
+    fail "Missing required --bfile parameter"
+fi
 
-plink --bfile "local" --bmerge "external.bed" "external.bim" "external.fam" --make-bed --noweb --out "HM3_b37merge"
+run_cmd() {
+    cmd="$*"
+
+    printf '%s\n' --------------------
+
+    if [ "$VERBOSE" = "1" ]; then
+	printf "$cmd\n"
+    fi
+
+    eval "$@"
+
+    EXIT_CODE=$?
+
+    if [[ $EXIT_CODE -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    fi
+
+    printf '%s\n' --------------------
+
+    return $EXIT_CODE
+}
+
+REFERENCE="/localdata/mds/HM3_b37"
+
+BFILE_FILTERED="$(basename ${BFILE}).filtered"
+
+run_cmd plink --bfile "${BFILE}" --hwe "1e-6" --geno "0.05" --maf "0.01" --noweb --make-bed --out ${BFILE_FILTERED}
+
+run_cmd "awk '{print \$2}' ${REFERENCE}.bim > HM3_b37.snplist.txt"
+
+run_cmd plink --bfile "${BFILE_FILTERED}" --extract HM3_b37.snplist.txt --make-bed --noweb --out "local"
+
+run_cmd "awk '{ \
+if ((\$5==\"T\" && \$6==\"A\") || (\$5==\"A\" && \$6==\"T\") || (\$5==\"C\" && \$6==\"G\") || (\$5==\"G\" && \$6==\"C\")) \
+print \$2, \"ambig\"; \
+else print \$2; \
+}' ${BFILE_FILTERED}.bim | grep -v ambig > local.snplist.txt"
+
+run_cmd plink --bfile "${REFERENCE}" --extract "local.snplist.txt" --make-bed --noweb --out external
+
+run_cmd plink --bfile "local" --bmerge "external.bed" "external.bim" "external.fam" --make-bed --noweb --out "HM3_b37merge"
 
 if [ -f "HM3_b37merge-merge.missnp" ]; then
 
-plink --bfile "local" --flip "HM3_b37merge-merge.missnp" --make-bed --noweb --out "flipped"
+    run_cmd plink --bfile "local" --flip "HM3_b37merge-merge.missnp" --make-bed --noweb --out "flipped"
 
-plink --bfile "flipped" --bmerge "external.bed" "external.bim" "external.fam" --make-bed --noweb --out "HM3_b37merge"
+    run_cmd plink --bfile "flipped" --bmerge "external.bed" "external.bim" "external.fam" --make-bed --noweb --out "HM3_b37merge"
 
 fi
 
-plink --bfile "HM3_b37merge" --cluster --mind "0.05" --mds-plot "4" --extract "local.snplist.txt" --noweb --out "HM3_b37mds"
+run_cmd plink --bfile "HM3_b37merge" --cluster --mind "0.05" --mds-plot "4" --extract "local.snplist.txt" --noweb --out "HM3_b37mds"
 
-awk 'BEGIN{OFS=","}; {print $1, $2, $3, $4, $5, $6, $7}' HM3_b37mds.mds >> HM3_b37mds2R.mds.csv
+run_cmd "awk 'BEGIN{OFS=\",\"}; {print \$1, \$2, \$3, \$4, \$5, \$6, \$7}' HM3_b37mds.mds >> HM3_b37mds2R.mds.csv"
 
-Rscript - <<EOF
+run_cmd 'Rscript - <<EOF
 library(calibrate)
 
 mds.cluster = read.csv("HM3_b37mds2R.mds.csv", header=T)
@@ -59,4 +112,4 @@ c("My Sample", "CEU", "CHB", "YRI", "TSI", "JPT", "CHD", "MEX", "GIH", "ASW","LW
 fill=c("red", "lightblue", "brown", "yellow", "green", "purple", "orange", "grey50", "black", "darkolivegreen", "magenta", "darkblue"))
 
 dev.off()
-EOF
+EOF'
diff --git a/bin/enigma-qc b/bin/enigma-qc
--- a/bin/enigma-qc
+++ b/bin/enigma-qc
@@ -1,29 +1,84 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-awk '{ \
-if (($5=="T" && $6=="A") || ($5=="A" && $6=="T") || ($5=="C" && $6=="G") || ($5=="G" && $6=="C")) \
-print $2, "ambig"; \
-else print $2; \
-}' "${datafileraw}.bim" | grep "ambig" | awk '{print $1}' > ambig.list
+OPTS=`getopt -o s:b:v --long study-name:,bfile:,verbose -n 'enigma-qc' -- "$@"`
+eval set -- "$OPTS"
 
-plink --bfile ${datafileraw} --exclude "ambig.list" --make-founders --out "lastQC" --maf 0.01 --hwe 0.000001 --make-bed --noweb
+VERBOSE=0
 
-awk '{print $2, $1":"$4}' "lastQC.bim" > updateSNPs.txt
+while true ; do
+    case "$1" in
+        -b|--bfile)
+            case "$2" in
+                "") shift 2 ;;
+                *) BFILE=$2 ; shift 2 ;;
+            esac ;;
+        -s|--study-name)
+            case "$2" in
+                "") shift 2 ;;
+                *) STUDY_NAME=$2 ; shift 2 ;;
+            esac ;;
+        -v|--verbose) VERBOSE=1 ; shift ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
 
-plink --bfile "lastQC" --update-name "updateSNPs.txt" --make-bed --out "lastQCb37" --noweb --list-duplicate-vars
-export lastqc="lastQCb37"
+fail() {
+    printf '%s\n' "$1" >&2    
+    exit "${2-1}"  
+}
 
-if [[ $(wc -l <lastQCb37.dupvar) -ge 1 ]]; then
-
-plink2 --bfile "lastQCb37" --rm-dup "exclude-mismatch" --out "lastQCb37_noduplicates" --make-bed
-export lastqc="lastQCb37_noduplicates"
-
+if [ ! -d /data/input ]; then
+    fail "Imputation server input folder \"/data/input\" does not exist. You should create it and try again"
 fi
 
-for i in {1..22}; do
+if [ ! $(ls -A /data/input) ]; then
+    fail "Imputation server input folder \"/data/input\" is not empty. You should check and/or backup its contents, run \"rm /data/input/*\", and try again"
+fi
 
-plink2 --bfile "${lastqc}" --chr "${i}" --recode "vcf" --out "${study_name}_chr${i}"
+if [[ ! -v STUDY_NAME ]]; then
+    fail "Missing required --study-name parameter"
+fi
 
-vcf-sort "${study_name}_chr${i}.vcf" | bgzip -c > /data/input/${study_name}_chr${i}.vcf.gz
+if [[ ! -v BFILE ]]; then
+    fail "Missing required --bfile parameter"
+fi
 
+run_cmd() {
+    cmd="$*"
+
+    printf '%s\n' --------------------
+
+    if [ "$VERBOSE" = "1" ]; then
+	printf "$cmd\n"
+    fi
+
+    eval "$@"
+
+    EXIT_CODE=$?
+
+    if [[ $EXIT_CODE -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    fi
+
+    printf '%s\n' --------------------
+
+    return $EXIT_CODE
+}
+
+run_cmd plink --bfile ${BFILE} --make-founders --out "lastQC" --maf 0.01 --hwe 0.000001 --make-bed --noweb
+
+run_cmd "awk '{print \$2, \$1\":\"\$4}' lastQC.bim > updateSNPs.txt"
+
+run_cmd plink --bfile "lastQC" --update-name "updateSNPs.txt" --make-bed --out "lastQCb37" --noweb --list-duplicate-vars
+
+export LASTQC="lastQCb37"
+if [[ $(wc -l <lastQCb37.dupvar) -ge 1 ]]; then
+    run_cmd plink2 --bfile "lastQCb37" --rm-dup "exclude-mismatch" --out "lastQCb37_noduplicates" --make-bed
+    export LASTQC="lastQCb37_noduplicates"
+fi
+
+for CHR in {1..22}; do
+    run_cmd plink2 --bfile "${LASTQC}" --chr "${CHR}" --recode "vcf" --out "${STUDY_NAME}_chr${CHR}"
+    run_cmd "vcf-sort ${STUDY_NAME}_chr${CHR}.vcf | bgzip -c > /data/input/${STUDY_NAME}_chr${CHR}.vcf.gz"
 done
diff --git a/bin/setup-hadoop b/bin/setup-hadoop
--- a/bin/setup-hadoop
+++ b/bin/setup-hadoop
@@ -1,24 +1,36 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-export CORES="4"
+OPTS=`getopt -o n: --long n-cores: -n 'setup-hadoop' -- "$@"`
+eval set -- "$OPTS"
+
+N_CORES=4
+
+while true ; do
+    case "$1" in
+        -n|--n-cores)
+            case "$2" in
+                "") shift 2 ;;
+                *) N_CORES=$2 ; shift 2 ;;
+            esac ;;
+        --) shift ; break ;;
+        *) echo "Internal error!" ; exit 1 ;;
+    esac
+done
 
 source /usr/lib/bigtop-utils/bigtop-detect-javahome
 
 export HADOOP_HOME=/usr/lib/hadoop
 export HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec
 
-mkdir -p -v logs
 export HADOOP_LOG_DIR=/data/logs
-
-mkdir -p -v pids
 export HADOOP_PID_DIR=/data/pids
-
-mkdir -p -v config
 export HADOOP_CONF_DIR=/data/config
+
+mkdir -p -v ${HADOOP_LOG_DIR} ${HADOOP_PID_DIR} ${HADOOP_CONF_DIR}
 
 cp -rnv ${HADOOP_HOME}/etc/hadoop/* ${HADOOP_CONF_DIR}
 
-sed -e s/AMOUNT/${CORES}/ -e s/HOSTNAME/localhost/ /usr/bin/mapred-site-template.xml > ${HADOOP_CONF_DIR}/mapred-site.xml
+sed -e s/AMOUNT/${N_CORES}/ -e s/HOSTNAME/localhost/ /usr/bin/mapred-site-template.xml > ${HADOOP_CONF_DIR}/mapred-site.xml
 
 sed s/HOSTNAME/localhost/ /usr/bin/core-site-template.xml > ${HADOOP_CONF_DIR}/core-site.xml
 
