Ensure that the `USER` environment variable is available

diff --git a/bin/imputationserver b/bin/imputationserver
--- a/bin/imputationserver
+++ b/bin/imputationserver
@@ -3,19 +3,19 @@
 OPTS=`getopt -o s:p: --long population:,study-name: -n 'imputationserver' -- "$@"`
 eval set -- "$OPTS"
 
-VERBOSE=1
+verbose=1
 
 while true ; do
     case "$1" in
         -s|--study-name)
             case "$2" in
                 "") shift 2 ;;
-                *) STUDY_NAME=$2 ; shift 2 ;;
+                *) study_name=$2 ; shift 2 ;;
             esac ;;
         -p|--population)
             case "$2" in
                 "") shift 2 ;;
-                *) POPULATION=$2 ; shift 2 ;;
+                *) population=$2 ; shift 2 ;;
             esac ;;
         --) shift ; break ;;
         *) echo "Internal error!" ; exit 1 ;;
@@ -27,11 +27,11 @@ fail() {
     exit "${2-1}"  
 }
 
-if [[ ! -v STUDY_NAME ]]; then
+if [[ ! -v study_name ]]; then
     fail "Missing required --study-name parameter"
 fi
 
-if [[ ! -v POPULATION ]]; then
+if [[ ! -v population ]]; then
     fail "Missing required --population parameter"
 fi
 
@@ -40,21 +40,21 @@ run_cmd() {
 
     printf '%s\n' --------------------
 
-    if [ "$VERBOSE" = "1" ]; then
+    if [ "$verbose" = "1" ]; then
 	printf "$cmd\n"
     fi
 
     ( "$@" )
 
-    EXIT_CODE=$?
+    exit_code=$?
 
-    if [[ $EXIT_CODE -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    if [[ ${exit_code} -gt 0 ]]; then
+	echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
 
-    return $EXIT_CODE
+    return ${exit_code}
 }
 
 # code starts here
@@ -62,17 +62,21 @@ run_cmd() {
 export PATH=/data/cloudgene:${PATH}
 export HADOOP_CONF_DIR=/data/hadoop/config
 
-EXTRA_FLAGS=""
-if [ "$VERBOSE" = "1" ]; then
-    EXTRA_FLAGS="--show-log --show-out"
+extra_flags=""
+if [ "$verbose" = "1" ]; then
+    extra_flags="--show-log --show-out"
 fi
 
-run_cmd mkdir -p -v /data/output/${STUDY_NAME}
+if [ -z "${USER}" ]; then 
+    export USER=$(whoami)
+fi
+
+run_cmd mkdir -p -v /data/output/${study_name}
 
 run_cmd cloudgene run imputationserver \
     --conf ${HADOOP_CONF_DIR} \
     --refpanel "1000g-phase-3-v5" \
-    --population ${POPULATION} \
-    --files "/data/input/${STUDY_NAME}" \
-    --output "/data/output/${STUDY_NAME}" \
-    --user ${USER} ${EXTRA_FLAGS}
+    --population ${population} \
+    --files "/data/input/${study_name}" \
+    --output "/data/output/${study_name}" \
+    --user ${USER} ${extra_flags}
