Add `--zstd-compress` option to `make-archive`
- Can reduce archive size by about sixty percent

diff --git a/bin/make-archive b/bin/make-archive
--- a/bin/make-archive
+++ b/bin/make-archive
@@ -1,19 +1,34 @@
 #!/usr/bin/env bash
 
-OPTS=`getopt -o s:p: --long study-name: -n 'make-archive' -- "$@"`
+OPTS=$(getopt -o s:p:z --long study-name:,zstd-compress -n 'make-archive' -- "$@")
 eval set -- "$OPTS"
 
-VERBOSE=1
+verbose=1
+zsdt_compress=0
 
-while true ; do
+while true; do
     case "$1" in
-        -s|--study-name)
-            case "$2" in
-                "") shift 2 ;;
-                *) STUDY_NAME=$2 ; shift 2 ;;
-            esac ;;
-        --) shift ; break ;;
-        *) echo "Internal error!" ; exit 1 ;;
+    -s | --study-name)
+        case "$2" in
+        "") shift 2 ;;
+        *)
+            study_name=$2
+            shift 2
+            ;;
+        esac
+        ;;
+    -z | --zstd-compress)
+        zsdt_compress=1
+        shift 1
+        ;;
+    --)
+        shift
+        break
+        ;;
+    *)
+        echo "Internal error!"
+        exit 1
+        ;;
     esac
 done
 
@@ -22,7 +37,7 @@ fail() {
     exit "${2-1}"
 }
 
-if [[ ! -v STUDY_NAME ]]; then
+if [[ ! -v study_name ]]; then
     fail "Missing required --study-name parameter"
 fi
 
@@ -31,37 +46,60 @@ run_cmd() {
 
     printf '%s\n' --------------------
 
-    if [ "$VERBOSE" = "1" ]; then
-	printf "$cmd\n"
+    if [ "${verbose}" = "1" ]; then
+        printf "$cmd\n"
     fi
 
-    ( "$@" )
+    ("$@")
 
-    EXIT_CODE=$?
+    exit_code=$?
 
-    if [[ $EXIT_CODE -gt 0 ]]; then
-	echo "ERROR: command exited with nonzero status $EXIT_CODE"
+    if [[ ${exit_code} -gt 0 ]]; then
+        echo "ERROR: command exited with nonzero status ${exit_code}"
     fi
 
     printf '%s\n' --------------------
 
-    return $EXIT_CODE
+    return ${exit_code}
 }
 
-ARCHIVE=/data/${STUDY_NAME}.zip
+#/data/
+archive=${study_name}.zip
 
 add_files() {
-    if [[ $# -eq 0 ]] ; then
+    if [[ $# -eq 0 ]]; then
         return
     fi
-    run_cmd 7za a ${ARCHIVE} $@
+    run_cmd 7z a ${archive} $@
 }
 
-add_files $(find /data/output/${STUDY_NAME}/{qcreport,statisticDir}/* 2>/dev/null)
+extract_and_add() {
+    a=$1
 
-for chr_file in $(find /data/output/${STUDY_NAME}/local/*.zip 2>/dev/null); do
     tmp_dir=$(mktemp -d)
-    run_cmd 7za -aoa -o${tmp_dir} -ppassword x ${chr_file}
-    add_files ${tmp_dir}/*
-    rm -rf ${tmp_dir}
+    run_cmd 7z -aoa -o${tmp_dir} -ppassword x ${a}
+
+    for v in $(find ${tmp_dir} -type f -name "*.dose.vcf.gz"); do
+        if [[ ${zsdt_compress} -eq 1 ]]; then
+            bgzip -c -d ${v} | zstd -T0 -B0 -f --ultra -22 -o "${tmp_dir}/$(basename ${v} .gz).zst"
+            run_cmd rm ${v}
+        else
+            run_cmd tabix -p vcf ${v}
+        fi
+    done
+
+    add_files \
+        $(find ${tmp_dir} -type f)
+    run_cmd rm -rf ${tmp_dir}
+}
+export -f extract_and_add
+
+# /data/
+output=output/${study_name}
+
+add_files ${output}/job.txt ${output}/std.out
+add_files $(find ${output}/{qcreport,statisticDir,logfile} -type f)
+
+for a in $(find ${output}/local -type f -name "chr_*.zip"); do
+    extract_and_add ${a}
 done
