Force reinstall of the imputation server to avoid error message `ERROR: Application or file imputationserver not found.`

diff --git a/bin/setup-imputationserver b/bin/setup-imputationserver
--- a/bin/setup-imputationserver
+++ b/bin/setup-imputationserver
@@ -37,6 +37,7 @@ if [ -z "$USER" ]; then
     USER=$(whoami)
 fi
 
+run_cmd rm -rf /data/cloudgene
 run_cmd mkdir -p -v /data/cloudgene /data/downloads
 run_cmd cp -rnv /opt/cloudgene/* /data/cloudgene/
 
@@ -62,16 +63,15 @@ if ! run_cmd cloudgene verify-cluster; then
 fi
 
 imputationserver_version="1.7.3"
-if [ ! -f /data/cloudgene/apps/imputationserver/${imputationserver_version}/imputationserver.jar ]; then
-    run_cmd wget --continue \
-        -O "/data/downloads/imputationserver-${imputationserver_version}.zip" \
-        "https://github.com/genepi/imputationserver/releases/download/v${imputationserver_version}/imputationserver.zip"
-    run_cmd cloudgene install /data/downloads/imputationserver-${imputationserver_version}.zip
+run_cmd wget --continue \
+    -O "/data/downloads/imputationserver-${imputationserver_version}.zip" \
+    "https://github.com/genepi/imputationserver/releases/download/v${imputationserver_version}/imputationserver.zip"
+if ! run_cmd cloudgene install /data/downloads/imputationserver-${imputationserver_version}.zip; then
+    fail "ERROR: Cloudgene could not install the imputation server"
 fi
 
-reference_version="3.0.0"
-if [ ! -f /data/cloudgene/apps/1000g-phase-3-v5/${reference_version}/imputation-1000genomes-phase3.yaml ]; then
-    run_cmd cloudgene install /localdata/imputationserver/1000genomes-phase3.zip
+if ! run_cmd cloudgene install /localdata/imputationserver/1000genomes-phase3.zip; then
+    fail "ERROR: Cloudgene could not install the reference genome"
 fi
 
 run_cmd "sed -i \"s/value: auto/value: password/g\" /data/cloudgene/apps/imputationserver/*/*.yaml"
